# Ebay Auto Market

    First, import pandas and NumPy libraries 
    Second, read the csv file as pandas dataframe
    Third, inspect the new dataframe.

In [1]:
import pandas as pd
import numpy as np

autos = pd.read_csv('autos.csv', encoding='Latin-1', parse_dates=True, index_col='dateCrawled')
autos.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 50000 entries, 2016-03-26 17:47:46 to 2016-03-14 00:42:12
Data columns (total 19 columns):
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(14)
memory usage: 7.6+ MB

In [2]:
autos.head(3)

,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
dateCrawled,,,,,,,,,,,,,,,,,,,
2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37

In [3]:
autos.columns

Index(['name', 'seller', 'offerType', 'price', 'abtest', 'vehicleType',
       'yearOfRegistration', 'gearbox', 'powerPS', 'model', 'odometer',
       'monthOfRegistration', 'fuelType', 'brand', 'notRepairedDamage',
       'dateCreated', 'nrOfPictures', 'postalCode', 'lastSeen'],
      dtype='object')

Uniform the column names to be easier to read.

In [5]:
cols = ['name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'powerPS', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen']
autos.columns = cols

autos.columns

Index(['name', 'seller', 'offer_type', 'price', 'abtest', 'vehicle_type',
       'registration_year', 'gearbox', 'powerPS', 'model', 'odometer',
       'registration_month', 'fuel_type', 'brand', 'unrepaired_damage',
       'ad_created', 'nr_of_pictures', 'postal_code', 'last_seen'],
      dtype='object')

In [6]:
autos.describe()

,registration_year,powerPS,registration_month,nr_of_pictures,postal_code
count,50000.000000,50000.000000,50000.000000,50000.0,50000.000000
mean,2005.073280,116.355920,5.723360,0.0,50813.627300
std,105.712813,209.216627,3.711984,0.0,25779.747957
min,1000.000000,0.000000,0.000000,0.0,1067.000000
25%,1999.000000,70.000000,3.000000,0.0,30451.000000
50%,2003.000000,105.000000,6.000000,0.0,49577.000000
75%,2008.000000,150.000000,9.000000,0.0,71540.000000
max,9999.000000,17700.000000,12.000000,0.0,99998.000000

In [7]:
autos['registration_year'].value_counts()

2000    3354
2005    3015
1999    3000
2004    2737
2003    2727
2006    2708
2001    2703
2002    2533
1998    2453
2007    2304
2008    2231
2009    2098
1997    2028
2011    1634
2010    1597
2017    1453
1996    1444
2012    1323
2016    1316
1995    1313
2013     806
2014     666
1994     660
2018     492
1993     445
2015     399
1990     395
1992     391
1991     356
1989     181
        ...
1950       3
1955       2
9000       2
1954       2
1800       2
1957       2
1941       2
1951       2
1934       2
4100       1
4800       1
1953       1
1111       1
1927       1
6200       1
4500       1
1943       1
5911       1
1939       1
1938       1
2800       1
8888       1
1000       1
1500       1
1948       1
1931       1
1929       1
1001       1
9996       1
1952       1
Name: registration_year, Length: 97, dtype: int64

In [8]:
autos.brand.value_counts()

volkswagen        10687
opel               5461
bmw                5429
mercedes_benz      4734
audi               4283
ford               3479
renault            2404
peugeot            1456
fiat               1308
seat                941
skoda               786
mazda               757
nissan              754
smart               701
citroen             701
toyota              617
sonstige_autos      546
hyundai             488
volvo               457
mini                424
mitsubishi          406
honda               399
kia                 356
alfa_romeo          329
porsche             294
suzuki              293
chevrolet           283
chrysler            181
dacia               129
daihatsu            128
jeep                110
subaru              109
land_rover           99
saab                 80
daewoo               79
trabant              78
jaguar               77
rover                69
lancia               57
lada                 31
Name: brand, dtype: int64

In [9]:
autosb = autos.copy()

In [10]:
brands = dict(autos['brand'].value_counts() > 1000)
m_brands = list(key for key, value in brands.items() if value == True)

print(m_brands)

['volkswagen', 'opel', 'bmw', 'mercedes_benz', 'audi', 'ford', 'renault', 'peugeot', 'fiat']

In [11]:
autos_major_brands = autos[autos['brand'].isin(m_brands)]

In [12]:
autos_major_brands.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 39241 entries, 2016-03-26 17:47:46 to 2016-03-14 00:42:12
Data columns (total 19 columns):
name                  39241 non-null object
seller                39241 non-null object
offer_type            39241 non-null object
price                 39241 non-null object
abtest                39241 non-null object
vehicle_type          35234 non-null object
registration_year     39241 non-null int64
gearbox               37264 non-null object
powerPS               39241 non-null int64
model                 37505 non-null object
odometer              39241 non-null object
registration_month    39241 non-null int64
fuel_type             35741 non-null object
brand                 39241 non-null object
unrepaired_damage     31316 non-null object
ad_created            39241 non-null object
nr_of_pictures        39241 non-null int64
postal_code           39241 non-null int64
last_seen             39241 non-null object
dtypes: int64(5), object(14)
memory usage: 6.0+ MB

In [13]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 50000 entries, 2016-03-26 17:47:46 to 2016-03-14 00:42:12
Data columns (total 19 columns):
name                  50000 non-null object
seller                50000 non-null object
offer_type            50000 non-null object
price                 50000 non-null object
abtest                50000 non-null object
vehicle_type          44905 non-null object
registration_year     50000 non-null int64
gearbox               47320 non-null object
powerPS               50000 non-null int64
model                 47242 non-null object
odometer              50000 non-null object
registration_month    50000 non-null int64
fuel_type             45518 non-null object
brand                 50000 non-null object
unrepaired_damage     40171 non-null object
ad_created            50000 non-null object
nr_of_pictures        50000 non-null int64
postal_code           50000 non-null int64
last_seen             50000 non-null object
dtypes: int64(5), object(14)
memory usage: 7.6+ MB

In [14]:
autos_major_brands['registration_year'].max()

9999

### Delete uotliers rows from years > 2018 or < 1901

In [15]:
autos = autos[(autos.registration_year < 2018)]

In [16]:
autos = autos[(autos.registration_year > 1901)]

In [17]:
autos['registration_year'].max()

2017

In [18]:
autos['registration_year'].min()

1910

In [19]:
autos.describe()

,registration_year,powerPS,registration_month,nr_of_pictures,postal_code
count,49481.000000,49481.000000,49481.000000,49481.0,49481.000000
mean,2003.220388,116.347265,5.733999,0.0,50868.169803
std,7.591016,197.350616,3.707758,0.0,25786.068077
min,1910.000000,0.000000,0.000000,0.0,1067.000000
25%,1999.000000,70.000000,3.000000,0.0,30457.000000
50%,2003.000000,105.000000,6.000000,0.0,49624.000000
75%,2008.000000,150.000000,9.000000,0.0,71636.000000
max,2017.000000,17700.000000,12.000000,0.0,99998.000000

In [20]:
autos.head()

,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
dateCrawled,,,,,,,,,,,,,,,,,,,
2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [21]:
autos.price = [x.strip('$') for x in autos.price]

In [22]:
autos.price = autos.price.str.replace(',','')

In [23]:
print(autos.price)

dateCrawled
2016-03-26 17:47:46     5000
2016-04-04 13:38:56     8500
2016-03-26 18:57:24     8990
2016-03-12 16:58:10     4350
2016-04-01 14:38:50     1350
2016-03-21 13:47:45     7900
2016-03-20 17:55:21      300
2016-03-16 18:55:19     1990
2016-03-22 16:51:34      250
2016-03-16 13:47:02      590
2016-03-15 01:41:36      999
2016-03-16 18:45:34      350
2016-03-31 19:48:22     5299
2016-03-23 10:48:32     1350
2016-03-23 11:50:46     3999
2016-04-01 12:06:20    18900
2016-03-16 14:59:02      350
2016-03-29 11:46:22     5500
2016-03-26 19:57:44      300
2016-03-17 13:36:21     4150
2016-03-05 19:57:31     3500
2016-03-06 19:07:10    41500
2016-03-28 20:50:54    25450
2016-03-10 19:55:34     7999
2016-04-03 11:57:02    48500
2016-03-21 21:56:18       90
2016-04-03 22:46:28      777
2016-03-27 18:45:01        0
2016-03-19 21:56:19     5250
2016-04-02 12:45:44     4999
                       ...
2016-03-21 22:47:37    15800
2016-03-29 14:54:12      950
2016-03-26 22:25:23     3300
2016-03-27 05:32:39     6000
2016-03-20 10:52:31        0
2016-03-27 20:51:39     9700
2016-03-19 18:56:05     5900
2016-03-31 18:37:18     5500
2016-04-04 10:37:14      900
2016-03-20 18:38:40    11000
2016-03-12 10:55:54      400
2016-03-15 09:38:21     2000
2016-03-29 18:51:08     1950
2016-03-06 12:43:04      600
2016-03-31 22:48:48        0
2016-04-02 16:38:23     1000
2016-04-04 20:46:02    15900
2016-03-22 20:47:27    21990
2016-03-28 19:49:51     9550
2016-03-11 19:50:37      150
2016-03-21 19:54:19    17500
2016-03-06 15:25:19      500
2016-03-10 19:37:38     4800
2016-03-15 18:47:35     1650
2016-03-22 17:36:42     5000
2016-03-27 14:38:19    24900
2016-03-28 10:50:25     1980
2016-04-02 14:44:48    13200
2016-03-08 19:25:42    22900
2016-03-14 00:42:12     1250
Name: price, Length: 49481, dtype: object

In [24]:
autos['price'] = pd.to_numeric(autos['price'])

In [25]:
autos.dtypes

name                  object
seller                object
offer_type            object
price                  int64
abtest                object
vehicle_type          object
registration_year      int64
gearbox               object
powerPS                int64
model                 object
odometer              object
registration_month     int64
fuel_type             object
brand                 object
unrepaired_damage     object
ad_created            object
nr_of_pictures         int64
postal_code            int64
last_seen             object
dtype: object

In [26]:
autos.sort_values(by='price', ascending=False)

,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
dateCrawled,,,,,,,,,,,,,,,,,,,
2016-03-22 14:58:27,Tausch_gegen_gleichwertiges,privat,Angebot,99999999,control,limousine,1999,automatik,224,s_klasse,"150,000km",9,benzin,mercedes_benz,NaN,2016-03-22 00:00:00,0,73525,2016-04-06 05:15:30
2016-03-08 20:39:05,Leasinguebernahme,privat,Angebot,27322222,control,limousine,2014,manuell,163,c4,"40,000km",2,diesel,citroen,NaN,2016-03-08 00:00:00,0,76532,2016-03-08 20:39:05
2016-03-09 15:45:47,Fiat_Punto,privat,Angebot,12345678,control,NaN,2017,NaN,95,punto,"150,000km",0,NaN,fiat,NaN,2016-03-09 00:00:00,0,96110,2016-03-09 15:45:47
2016-03-31 18:56:54,Opel_Vectra_B_1_6i_16V_Facelift_Tuning_Showcar...,privat,Angebot,12345678,control,limousine,2001,manuell,101,vectra,"150,000km",3,benzin,opel,nein,2016-03-31 00:00:00,0,4356,2016-03-31 18:56:54
2016-03-21 13:57:51,Schlachte_Golf_3_gt_tdi,privat,Angebot,11111111,test,NaN,1995,NaN,0,NaN,"150,000km",0,NaN,volkswagen,NaN,2016-03-21 00:00:00,0,18519,2016-03-21 14:40:18
2016-03-12 21:50:57,Escort_MK_1_Hundeknochen_zum_umbauen_auf_RS_2000,privat,Angebot,11111111,test,limousine,1973,manuell,48,escort,"50,000km",3,benzin,ford,nein,2016-03-12 00:00:00,0,94469,2016-03-12 22:45:27
2016-03-29 23:52:57,suche_maserati_3200_gt_Zustand_unwichtig_laufe...,privat,Angebot,10000000,control,coupe,1960,manuell,368,NaN,"100,000km",1,benzin,sonstige_autos,nein,2016-03-29 00:00:00,0,73033,2016-04-06 21:18:11
2016-04-04 21:25:21,Ferrari_FXX,privat,Angebot,3890000,test,coupe,2006,NaN,799,NaN,"5,000km",7,NaN,sonstige_autos,nein,2016-04-04 00:00:00,0,60313,2016-04-05 12:07:37
2016-04-04 11:53:31,Ferrari_F40,privat,Angebot,1300000,control,coupe,1992,NaN,0,NaN,"50,000km",12,NaN,sonstige_autos,nein,2016-04-04 00:00:00,0,60598,2016-04-05 11:34:11
2016-03-22 12:54:19,Bmw_530d_zum_ausschlachten,privat,Angebot,1234566,control,kombi,1999,automatik,190,NaN,"150,000km",2,diesel,bmw,NaN,2016-03-22 00:00:00,0,17454,2016-04-02 03:17:32
2016-03-21 19:53:52,2_VW_Busse_T3,privat,Angebot,999999,test,bus,1981,manuell,70,transporter,"150,000km",1,benzin,volkswagen,NaN,2016-03-21 00:00:00,0,99880,2016-03-28 17:18:28
2016-03-17 09:53:08,Ford_Focus_Turnier_1.6_16V_Style,privat,Angebot,999999,test,kombi,2009,manuell,101,focus,"125,000km",4,benzin,ford,nein,2016-03-17 00:00:00,0,12205,2016-04-06 07:17:35
2016-03-29 11:38:54,Volkswagen_Jetta_GT,privat,Angebot,999990,test,limousine,1985,manuell,111,jetta,"150,000km",12,benzin,volkswagen,ja,2016-03-29 00:00:00,0,50997,2016-03-29 11:38:54
2016-03-27 18:37:37,Porsche_991,privat,Angebot,350000,control,coupe,2016,manuell,500,911,"5,000km",3,benzin,porsche,nein,2016-03-27 00:00:00,0,70499,2016-03-27 18:37:37
2016-03-30 08:37:24,Rolls_Royce_Phantom_Drophead_Coupe,privat,Angebot,345000,control,cabrio,2012,automatik,460,NaN,"20,000km",8,benzin,sonstige_autos,nein,2016-03-30 00:00:00,0,73525,2016-04-07 00:16:26
2016-03-23 16:37:29,Porsche_Porsche_911/930_Turbo_3.0__deutsche_Au...,privat,Angebot,299000,test,coupe,1977,manuell,260,911,"100,000km",7,benzin,porsche,nein,2016-03-23 00:00:00,0,61462,2016-04-06 16:44:50
2016-04-03 07:56:23,Porsche_911_Targa_Exclusive_Edition__1_von_15_...,privat,Angebot,295000,test,cabrio,2015,automatik,400,911,"5,000km",6,benzin,porsche,nein,2016-04-03 00:00:00,0,74078,2016-04-03 08:56:20
2016-03-28 22:48:01,Porsche_GT3_RS__PCCB__Lift___grosser_Exklusiv_...,privat,Angebot,265000,control,coupe,2016,automatik,500,911,"5,000km",3,benzin,porsche,nein,2016-03-28 00:00:00,0,70193,2016-04-05 03:44:51
2016-04-05 10:25:38,BMW_Z8_roadster,privat,Angebot,259000,test,cabrio,2001,manuell,400,z_reihe,"20,000km",6,benzin,bmw,nein,2016-04-05 00:00:00,0,61462,2016-04-05 12:07:32
2016-03-28 22:25:25,Glas_BMW_mit_Wasser,privat,Angebot,250000,test,NaN,2015,NaN,0,x_reihe,"5,000km",0,NaN,bmw,NaN,2016-03-28 00:00:00,0,60489,2016-03-28 22:25:25
2016-03-21 10:50:12,Porsche_997,privat,Angebot,220000,test,coupe,2008,manuell,415,911,"30,000km",7,benzin,porsche,nein,2016-03-21 00:00:00,0,69198,2016-04-06 04:46:14
2016-03-20 18:40:05,Porsche_911_991_GT3_RS,privat,Angebot,198000,test,coupe,2015,automatik,500,911,"5,000km",6,benzin,porsche,nein,2016-03-20 00:00:00,0,51491,2016-03-21 21:46:36
2016-03-16 18:47:26,Porsche_993/911_Turbo_WLS_II_Exclusive_S_deuts...,privat,Angebot,197000,control,coupe,1998,manuell,450,911,"150,000km",3,NaN,porsche,nein,2016-03-16 00:00:00,0,46147,2016-04-07 02:44:47
2016-03-08 19:50:06,Tesla_Model_X_P90D_Signature_Sondermodel__Neuw...,privat,Angebot,194000,test,suv,2016,automatik,0,NaN,"5,000km",3,elektro,sonstige_autos,nein,2016-03-08 00:00:00,0,97990,2016-03-16 04:15:31
2016-03-22 17:47:59,BMW_Z8_roadster,privat,Angebot,190000,control,cabrio,2000,manuell,400,z_reihe,"60,000km",9,benzin,bmw,nein,2016-03-22 00:00:00,0,14473,2016-04-02 11:44:28
2016-03-05 17:39:22,Mercedes_Benz_SLS_AMG_Roadster_AMG_SPEEDSHIFT_DCT,privat,Angebot,180000,test,cabrio,2012,automatik,571,andere,"50,000km",2,benzin,mercedes_benz,nein,2016-03-05 00:00:00,0,14193,2016-03-20 19:44:36
2016-03-30 21:44:21,Audi_R8_V10_plus_5.2_FSI_quattro_S_tronic_Akra...,privat,Angebot,175000,test,coupe,2016,automatik,610,andere,"5,000km",1,benzin,audi,nein,2016-03-30 00:00:00,0,94244,2016-04-05 11:46:33
2016-03-22 08:55:27,Mercedes_Benz_G_500_7G_TRONIC_Cabrio_Desingno_...,privat,Angebot,169999,control,cabrio,2012,automatik,387,g_klasse,"40,000km",3,benzin,mercedes_benz,nein,2016-03-22 00:00:00,0,42655,2016-04-05 20:47:17
2016-03-27 18:43:02,Porsche_991_GT3,privat,Angebot,169000,control,coupe,2013,automatik,476,911,"20,000km",9,benzin,porsche,nein,2016-03-27 00:00:00,0,83629,2016-04-05 15:15:29
2016-03-05 18:40:13,Porsche_911_991_GT3_LED_Licht_Chrono_Navi_Club...,privat,Angebot,163991,test,coupe,2014,automatik,476,911,"10,000km",6,benzin,porsche,nein,2016-03-05 00:00:00,0,51702,2016-03-09 16:45:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-03-08 10:47:41,OPEL_VECTRA_A_CC._123000_km_aus_erster_Hand,privat,Angebot,0,test,limousine,1994,manuell,83,vectra,"125,000km",6,benzin,opel,NaN,2016-03-08 00:00:00,0,14806,2016-03-08 17:16:53
2016-03-20 15:56:22,Vw_Passat_1.8_turbo,privat,Angebot,0,control,kombi,1997,manuell,150,passat,"150,000km",0,NaN,volkswagen,nein,2016-03-20 00:00:00,0,66333,2016-04-01 00:17:01
2016-03-11 11:40:40,Twingo_1.2_TÜV_neu_tauschen/verkaufen,privat,Angebot,0,test,kleinwagen,2000,manuell,58,twingo,"150,000km",10,benzin,renault,nein,2016-03-10 00:00:00,0,55422,2016-03-22 12:47:19
2016-03-14 16:25:21,Wer_kann_Lichtmaschine_reparieren!!!,privat,Angebot,0,test,NaN,2005,NaN,90,galaxy,"5,000km",3,diesel,ford,NaN,2016-03-14 00:00:00,0,60488,2016-03-14 18:46:11
2016-03-12 19:51:26,3er.Golf_dunkelgruen,privat,Angebot,0,test,limousine,1997,automatik,0,golf,"150,000km",0,benzin,volkswagen,nein,2016-03-12 00:00:00,0,75378,2016-03-12 19:51:26
2016-03-14 20:43:15,Unfall_Audi_A3,privat,Angebot,0,control,kleinwagen,1997,manuell,125,a3,"5,000km",1,benzin,audi,ja,2016-03-14 00:00:00,0,71726,2016-04-06 07:46:03
2016-03-12 17:55:26,BMW_120D_xDrive_zu_verkaufen,privat,Angebot,0,test,limousine,2012,manuell,184,1er,"40,000km",8,diesel,bmw,nein,2016-03-12 00:00:00,0,89150,2016-03-14 10:18:59
2016-03-24 13:51:55,SUCHE_fuer_TT8N,privat,Angebot,0,control,coupe,2000,manuell,0,tt,"5,000km",12,benzin,audi,nein,2016-03-24 00:00:00,0,61169,2016-04-05 23:46:41
2016-03-28 18:59:11,Volvo_V70__S__Teilleder_Klima___eventuell_auch...,privat,Angebot,0,control,kombi,1998,manuell,192,v70,"150,000km",8,benzin,volvo,nein,2016-03-28 00:00:00,0,49696,2016-04-01 04:46:04
2016-03-05 14:40:53,VW_Passat_Automatik__Tiptronik__Gruene_Plakett...,privat,Angebot,0,control,limousine,2000,automatik,115,passat,"150,000km",2,diesel,volkswagen,nein,2016-03-05 00:00:00,0,4651,2016-03-16 21:46:38
2016-03-07 14:38:31,Marcedes_vito_108_cdi,privat,Angebot,0,control,bus,2000,manuell,0,vito,"150,000km",10,diesel,mercedes_benz,NaN,2016-03-07 00:00:00,0,6780,2016-04-07 01:16:49
2016-03-22 01:36:19,TAUSCHE_HIER_Ford_Focus_Turnier_Kombi_1.6_TÜV_...,privat,Angebot,0,test,kombi,2000,manuell,101,focus,"150,000km",9,benzin,ford,NaN,2016-03-22 00:00:00,0,58452,2016-03-22 08:45:48
2016-03-07 09:53:47,Bastler_Auto,privat,Angebot,0,control,kleinwagen,1996,manuell,45,NaN,"150,000km",0,benzin,opel,NaN,2016-03-07 00:00:00,0,32549,2016-03-16 17:20:06
2016-03-20 18:50:57,3_BMWs_zu_Verkaufen,privat,Angebot,0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,bmw,NaN,2016-03-20 00:00:00,0,87616,2016-03-20 18:50:57
2016-04-02 13:56:18,Tausche_gegen_e34_e36_e39__e46,privat,Angebot,0,test,NaN,2011,NaN,0,NaN,"50,000km",0,NaN,bmw,NaN,2016-04-02 00:00:00,0,88512,2016-04-02 13:56:18
2016-03-08 15:47:39,Renault_Twingo_RS_Sport,privat,Angebot,0,test,kleinwagen,2010,manuell,133,twingo,"30,000km",9,benzin,renault,nein,2016-03-08 00:00:00,0,30559,2016-03-09 23:46:45
2016-03-29 04:03:40,Nissan_Navara_D40_/_King_Cab_mit_Harttop,privat,Angebot,0,test,suv,2006,manuell,174,navara,"150,000km",8,diesel,nissan,nein,2016-03-29 00:00:00,0,34302,2016-04-05 17:25:58
2016-03-07 13:51:59,Nissan_Primera_Xenon_und_Klimaautomatik,privat,Angebot,0,control,limousine,2000,manuell,150,primera,"150,000km",6,benzin,nissan,nein,2016-03-07 00:00:00,0,12053,2016-03-09 06:46:27
2016-03-11 01:50:15,Schlachtfest_oder_komplett_zu_verkaufen,privat,Angebot,0,test,limousine,1992,manuell,150,100,"150,000km",0,benzin,audi,ja,2016-03-10 00:00:00,0,93080,2016-04-05 23:46:31
2016-03-10 11:53:04,Tadelloser_BMW_Z3_1_9er_140_PS__Rotes_Leder__T...,privat,Angebot,0,test,cabrio,1997,manuell,140,z_reihe,"150,000km",6,benzin,bmw,nein,2016-03-10 00:00:00,0,50674,2016-03-14 07:16:23
2016-04-03 21:48:28,Tausch/Verkaufe_bmw_e36_Coupe,privat,Angebot,0,test,coupe,1995,manuell,102,3er,"150,000km",1,benzin,bmw,ja,2016-04-03 00:00:00,0,25885,2016-04-05 22:47:40
2016-03-12 16:41:03,Ich_moechte_verkaufen_mein_Auto_biss_15.3.2016,privat,Angebot,0,control,limousine,1999,manuell,75,golf,"150,000km",7,benzin,volkswagen,nein,2016-03-12 00:00:00,0,22049,2016-03-15 02:44:42
2016-03-28 10:48:54,Ford_Mustang_GT_V8_Teile_bj._94_98,privat,Angebot,0,control,NaN,2000,manuell,214,mustang,"50,000km",7,benzin,ford,ja,2016-03-28 00:00:00,0,79106,2016-04-06 12:45:13
2016-04-01 21:50:34,Verkaufe_BMW_e36,privat,Angebot,0,test,limousine,1996,manuell,116,3er,"150,000km",9,benzin,bmw,nein,2016-04-01 00:00:00,0,84137,2016-04-05 19:46:21
2016-03-09 13:52:10,BMW_320_DTouring,privat,Angebot,0,control,kombi,2003,automatik,150,3er,"150,000km",10,diesel,bmw,ja,2016-03-09 00:00:00,0,22547,2016-03-09 13:52:10
2016-03-27 14:50:41,Trabant_Kombi,privat,Angebot,0,control,kombi,1972,manuell,26,601,"150,000km",0,NaN,trabant,NaN,2016-03-27 00:00:00,0,93086,2016-04-07 11:45:08
2016-03-05 22:54:03,Lackierer_sucht_Auftraege,privat,Angebot,0,control,NaN,1960,NaN,0,NaN,"10,000km",0,NaN,sonstige_autos,NaN,2016-03-05 00:00:00,0,72622,2016-03-06 05:43:10
2016-03-11 19:50:48,Opel_vectra_b_super_Zustand,privat,Angebot,0,test,limousine,1998,automatik,170,vectra,"150,000km",5,benzin,opel,nein,2016-03-11 00:00:00,0,32369,2016-03-13 01:16:48
2016-03-29 21:38:39,Vw_Golf_3_Bon_Jovi,privat,Angebot,0,test,NaN,2000,NaN,0,golf,"150,000km",0,NaN,volkswagen,NaN,2016-03-29 00:00:00,0,94164,2016-03-31 15:16:54
2016-03-27 17:47:28,Golf_IV_Limousine,privat,Angebot,0,test,limousine,2001,manuell,75,golf,"150,000km",0,benzin,volkswagen,NaN,2016-03-27 00:00:00,0,93336,2016-03-27 17:47:28

In [27]:
autos = autos[(autos.price < 500000)]

In [28]:
autos.sort_values(by='price', ascending=False)

,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
dateCrawled,,,,,,,,,,,,,,,,,,,
2016-03-27 18:37:37,Porsche_991,privat,Angebot,350000,control,coupe,2016,manuell,500,911,"5,000km",3,benzin,porsche,nein,2016-03-27 00:00:00,0,70499,2016-03-27 18:37:37
2016-03-30 08:37:24,Rolls_Royce_Phantom_Drophead_Coupe,privat,Angebot,345000,control,cabrio,2012,automatik,460,NaN,"20,000km",8,benzin,sonstige_autos,nein,2016-03-30 00:00:00,0,73525,2016-04-07 00:16:26
2016-03-23 16:37:29,Porsche_Porsche_911/930_Turbo_3.0__deutsche_Au...,privat,Angebot,299000,test,coupe,1977,manuell,260,911,"100,000km",7,benzin,porsche,nein,2016-03-23 00:00:00,0,61462,2016-04-06 16:44:50
2016-04-03 07:56:23,Porsche_911_Targa_Exclusive_Edition__1_von_15_...,privat,Angebot,295000,test,cabrio,2015,automatik,400,911,"5,000km",6,benzin,porsche,nein,2016-04-03 00:00:00,0,74078,2016-04-03 08:56:20
2016-03-28 22:48:01,Porsche_GT3_RS__PCCB__Lift___grosser_Exklusiv_...,privat,Angebot,265000,control,coupe,2016,automatik,500,911,"5,000km",3,benzin,porsche,nein,2016-03-28 00:00:00,0,70193,2016-04-05 03:44:51
2016-04-05 10:25:38,BMW_Z8_roadster,privat,Angebot,259000,test,cabrio,2001,manuell,400,z_reihe,"20,000km",6,benzin,bmw,nein,2016-04-05 00:00:00,0,61462,2016-04-05 12:07:32
2016-03-28 22:25:25,Glas_BMW_mit_Wasser,privat,Angebot,250000,test,NaN,2015,NaN,0,x_reihe,"5,000km",0,NaN,bmw,NaN,2016-03-28 00:00:00,0,60489,2016-03-28 22:25:25
2016-03-21 10:50:12,Porsche_997,privat,Angebot,220000,test,coupe,2008,manuell,415,911,"30,000km",7,benzin,porsche,nein,2016-03-21 00:00:00,0,69198,2016-04-06 04:46:14
2016-03-20 18:40:05,Porsche_911_991_GT3_RS,privat,Angebot,198000,test,coupe,2015,automatik,500,911,"5,000km",6,benzin,porsche,nein,2016-03-20 00:00:00,0,51491,2016-03-21 21:46:36
2016-03-16 18:47:26,Porsche_993/911_Turbo_WLS_II_Exclusive_S_deuts...,privat,Angebot,197000,control,coupe,1998,manuell,450,911,"150,000km",3,NaN,porsche,nein,2016-03-16 00:00:00,0,46147,2016-04-07 02:44:47
2016-03-08 19:50:06,Tesla_Model_X_P90D_Signature_Sondermodel__Neuw...,privat,Angebot,194000,test,suv,2016,automatik,0,NaN,"5,000km",3,elektro,sonstige_autos,nein,2016-03-08 00:00:00,0,97990,2016-03-16 04:15:31
2016-03-22 17:47:59,BMW_Z8_roadster,privat,Angebot,190000,control,cabrio,2000,manuell,400,z_reihe,"60,000km",9,benzin,bmw,nein,2016-03-22 00:00:00,0,14473,2016-04-02 11:44:28
2016-03-05 17:39:22,Mercedes_Benz_SLS_AMG_Roadster_AMG_SPEEDSHIFT_DCT,privat,Angebot,180000,test,cabrio,2012,automatik,571,andere,"50,000km",2,benzin,mercedes_benz,nein,2016-03-05 00:00:00,0,14193,2016-03-20 19:44:36
2016-03-30 21:44:21,Audi_R8_V10_plus_5.2_FSI_quattro_S_tronic_Akra...,privat,Angebot,175000,test,coupe,2016,automatik,610,andere,"5,000km",1,benzin,audi,nein,2016-03-30 00:00:00,0,94244,2016-04-05 11:46:33
2016-03-22 08:55:27,Mercedes_Benz_G_500_7G_TRONIC_Cabrio_Desingno_...,privat,Angebot,169999,control,cabrio,2012,automatik,387,g_klasse,"40,000km",3,benzin,mercedes_benz,nein,2016-03-22 00:00:00,0,42655,2016-04-05 20:47:17
2016-03-27 18:43:02,Porsche_991_GT3,privat,Angebot,169000,control,coupe,2013,automatik,476,911,"20,000km",9,benzin,porsche,nein,2016-03-27 00:00:00,0,83629,2016-04-05 15:15:29
2016-03-05 18:40:13,Porsche_911_991_GT3_LED_Licht_Chrono_Navi_Club...,privat,Angebot,163991,test,coupe,2014,automatik,476,911,"10,000km",6,benzin,porsche,nein,2016-03-05 00:00:00,0,51702,2016-03-09 16:45:30
2016-03-18 16:41:22,Porsche_911_GT3__Clubsp._Lift_nur_bis_25.03._v...,privat,Angebot,163500,test,coupe,2015,automatik,476,911,"10,000km",9,benzin,porsche,nein,2016-03-18 00:00:00,0,74078,2016-03-18 16:41:22
2016-03-17 12:56:38,Porsche_991,privat,Angebot,155000,test,coupe,2013,NaN,476,911,"20,000km",11,NaN,porsche,nein,2016-03-17 00:00:00,0,90768,2016-03-26 23:16:41
2016-03-24 12:54:19,Porsche_911_GT3_RS,privat,Angebot,151990,test,coupe,2007,manuell,415,911,"20,000km",10,benzin,porsche,nein,2016-03-24 00:00:00,0,40479,2016-04-07 03:46:46
2016-03-31 13:45:02,"Porsche_911__993__Carrera_S_""SONDERMODELL""",privat,Angebot,145000,control,coupe,1998,manuell,286,911,"60,000km",7,benzin,porsche,nein,2016-03-31 00:00:00,0,63179,2016-04-06 06:16:03
2016-03-25 12:42:09,Porsche_997_GT3_MKII_EIN_SAMMLERSTÜCK_IN_VOLLA...,privat,Angebot,139997,test,coupe,2010,manuell,435,911,"20,000km",3,benzin,porsche,nein,2016-03-25 00:00:00,0,71159,2016-04-06 13:45:07
2016-03-21 22:51:29,Porsche_911_GT3,privat,Angebot,137999,control,coupe,2010,manuell,435,911,"20,000km",7,benzin,porsche,nein,2016-03-21 00:00:00,0,80636,2016-04-07 05:45:39
2016-04-01 12:52:27,Porsche_997_GT3_Approved_Lift_Unfallfrei_Mj.2011,privat,Angebot,135000,test,coupe,2010,manuell,435,911,"30,000km",7,benzin,porsche,nein,2016-04-01 00:00:00,0,83684,2016-04-07 09:44:21
2016-03-08 10:06:22,SUCHE_TIPPS___Ford_Mustang_Shelby_GT_350_500_K...,privat,Angebot,130000,control,coupe,1968,NaN,0,mustang,"50,000km",7,benzin,ford,NaN,2016-03-08 00:00:00,0,56070,2016-03-23 23:15:17
2016-03-12 16:58:37,Porsche_911_Turbo,privat,Angebot,129000,control,coupe,1995,manuell,408,911,"125,000km",9,benzin,porsche,nein,2016-03-12 00:00:00,0,70180,2016-04-05 04:49:19
2016-04-01 21:50:47,Porsche_993_S_Schalter_BRD_neuwertig,privat,Angebot,128000,test,coupe,1997,manuell,286,911,"100,000km",4,benzin,porsche,nein,2016-04-01 00:00:00,0,81543,2016-04-05 19:46:23
2016-03-15 10:52:35,Porsche_911___993_4S,privat,Angebot,120000,control,coupe,1998,manuell,286,911,"125,000km",3,benzin,porsche,nein,2016-03-15 00:00:00,0,25488,2016-04-05 19:47:31
2016-03-15 14:47:26,Mercedes_Benz_170_S_Cabriolet_A__Startklar_fue...,privat,Angebot,120000,control,cabrio,1951,manuell,52,andere,"20,000km",5,benzin,mercedes_benz,nein,2016-03-15 00:00:00,0,1067,2016-04-06 05:15:50
2016-04-03 18:42:28,Porsche_911_Carrera_4S_Cabriolet_PDK,privat,Angebot,119900,control,cabrio,2014,automatik,400,911,"30,000km",2,benzin,porsche,nein,2016-04-03 00:00:00,0,51465,2016-04-05 18:46:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-03-07 17:48:03,Volvo_v40,privat,Angebot,0,test,kombi,1998,manuell,115,v40,"150,000km",2,NaN,volvo,nein,2016-03-07 00:00:00,0,4680,2016-03-13 04:45:14
2016-03-25 00:56:39,Golf_3_cabrio_tausche,privat,Angebot,0,control,cabrio,1994,manuell,100,golf,"150,000km",4,benzin,volkswagen,nein,2016-03-24 00:00:00,0,16727,2016-04-06 06:17:24
2016-04-02 23:52:53,Trabant_Karosse,privat,Angebot,0,test,NaN,1985,NaN,0,601,"100,000km",0,NaN,trabant,NaN,2016-04-02 00:00:00,0,1936,2016-04-03 06:41:53
2016-03-19 07:53:19,BMW_COMPACT_DIESEL_FACELIFT_gruene_Plakette_Ta...,privat,Angebot,0,control,coupe,2004,manuell,115,3er,"150,000km",10,diesel,bmw,NaN,2016-03-19 00:00:00,0,44263,2016-03-20 10:48:56
2016-03-25 11:36:20,Sonderangebot_VW_Beetle_1999_TÜV_1/18_Anliefer...,privat,Angebot,0,test,kleinwagen,1999,manuell,115,beetle,"150,000km",1,benzin,volkswagen,nein,2016-03-25 00:00:00,0,31582,2016-04-06 11:17:54
2016-03-06 00:54:53,Zer_Guten_Auto_800_,privat,Angebot,0,control,NaN,2016,NaN,0,NaN,"5,000km",0,NaN,chevrolet,NaN,2016-03-06 00:00:00,0,28325,2016-03-06 00:54:53
2016-03-20 13:53:31,fiat_pumto_188_zum_ausschlachten,privat,Angebot,0,test,kleinwagen,2002,manuell,60,punto,"125,000km",5,benzin,fiat,NaN,2016-03-20 00:00:00,0,42719,2016-04-06 15:45:34
2016-03-31 19:54:14,Nissan_Navara_zum_ausschlachten,privat,Angebot,0,control,suv,1999,manuell,103,navara,"150,000km",6,diesel,nissan,NaN,2016-03-31 00:00:00,0,49638,2016-04-06 14:18:04
2016-03-08 18:36:40,Renault_Megane_Classic,privat,Angebot,0,test,limousine,1997,manuell,75,megane,"150,000km",7,benzin,renault,NaN,2016-03-08 00:00:00,0,14943,2016-03-19 21:47:18
2016-03-15 20:45:23,Lexus_GS_300,privat,Angebot,0,test,limousine,1994,automatik,212,NaN,"150,000km",6,benzin,sonstige_autos,NaN,2016-03-15 00:00:00,0,39120,2016-03-27 08:15:53
2016-03-05 22:51:46,Peugeot_F_206_TÜV_&_AU_gestern_neu_Euro_4_Soun...,privat,Angebot,0,control,kleinwagen,1999,manuell,75,2_reihe,"5,000km",10,benzin,peugeot,nein,2016-03-05 00:00:00,0,14550,2016-04-07 03:46:19
2016-03-19 09:39:15,BMW_E39_520_Tempomat_Xenon_TÜV_4/17_188.000km,privat,Angebot,0,test,limousine,1996,manuell,150,5er,"150,000km",6,benzin,bmw,nein,2016-03-19 00:00:00,0,57072,2016-03-31 14:46:21
2016-03-14 18:40:37,Rennwagen___Golf_3,privat,Angebot,0,test,kleinwagen,1992,manuell,0,golf,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,39104,2016-03-17 07:46:54
2016-03-07 17:41:44,Ersatzteilspender_/_Schlachtfahrzeug,privat,Angebot,0,test,limousine,1993,manuell,90,escort,"125,000km",8,benzin,ford,ja,2016-03-07 00:00:00,0,6667,2016-04-06 05:16:48
2016-04-06 23:25:34,Focus_mk1_klappert_vorn?,privat,Angebot,0,control,NaN,2000,NaN,0,focus,"5,000km",0,NaN,ford,NaN,2016-04-06 00:00:00,0,56575,2016-04-07 00:25:16
2016-03-25 12:47:00,Opel_Zafira_OPC_LET/LEH_Turbo,privat,Angebot,0,test,bus,2003,manuell,260,zafira,"150,000km",0,benzin,opel,nein,2016-03-25 00:00:00,0,97877,2016-03-28 11:45:21
2016-04-04 19:44:22,Bmw_e46_320i_touring_mit_unfallschaden,privat,Angebot,0,test,kombi,2000,manuell,150,3er,"150,000km",12,benzin,bmw,ja,2016-04-04 00:00:00,0,27619,2016-04-04 19:44:22
2016-04-02 23:36:34,Seat_Ibiza_BJ_2001_Ausschlachtfahrzeug,privat,Angebot,0,test,kleinwagen,2001,manuell,90,ibiza,"150,000km",0,diesel,seat,ja,2016-04-02 00:00:00,0,29303,2016-04-07 09:15:40
2016-03-17 10:52:53,Verkaufe_oder_Tausche_mein_Bmw,privat,Angebot,0,test,cabrio,1996,NaN,0,3er,"150,000km",0,NaN,bmw,NaN,2016-03-17 00:00:00,0,6193,2016-03-22 18:45:38
2016-03-22 11:56:10,Karosse_Ford_Mondeo,privat,Angebot,0,control,kombi,2004,NaN,130,mondeo,"125,000km",12,diesel,ford,NaN,2016-03-22 00:00:00,0,66773,2016-03-29 14:45:44
2016-03-30 13:55:32,Opel_Corsa_C_1__2_Liter_mit_Klima_TÜV_bis_10.2017,privat,Angebot,0,test,NaN,2005,NaN,75,corsa,"150,000km",5,NaN,opel,NaN,2016-03-30 00:00:00,0,49477,2016-03-30 14:42:13
2016-04-01 10:53:56,Audi_A4_1.8,privat,Angebot,0,control,NaN,1995,manuell,125,a4,"150,000km",4,NaN,audi,NaN,2016-04-01 00:00:00,0,94333,2016-04-07 08:15:27
2016-03-09 14:38:53,Ersatzteile_Opel_corsa_b_fuer_jeden_Preis_offen,privat,Angebot,0,test,NaN,2000,NaN,0,corsa,"5,000km",0,NaN,opel,NaN,2016-03-09 00:00:00,0,92318,2016-04-06 08:15:59
2016-03-12 19:50:09,Tausche_Auto_PKW_Opel_Corsa_B_Edition_2000_all...,privat,Angebot,0,test,kleinwagen,2000,manuell,55,corsa,"150,000km",10,benzin,opel,nein,2016-03-12 00:00:00,0,8340,2016-03-12 19:50:09
2016-03-12 10:49:22,Golf_3_1_9_GTI_TDI_Jubi_20Jah_Edition_144PS_TÜ...,privat,Angebot,0,control,NaN,2017,manuell,144,golf,"150,000km",12,NaN,volkswagen,nein,2016-03-12 00:00:00,0,46325,2016-03-22 13:50:10
2016-03-15 09:37:16,Opel_astra_f_cc_3_tuerer,privat,Angebot,0,control,NaN,2017,manuell,60,astra,"150,000km",0,benzin,opel,NaN,2016-03-15 00:00:00,0,99510,2016-03-31 02:47:01
2016-03-17 13:52:04,Polo_6n_Open_air,privat,Angebot,0,control,kleinwagen,1998,manuell,45,polo,"150,000km",8,benzin,volkswagen,ja,2016-03-17 00:00:00,0,21379,2016-04-06 19:47:10
2016-03-23 14:46:47,Golf_3_1.6l,privat,Angebot,0,test,kleinwagen,1996,manuell,75,golf,"150,000km",0,benzin,volkswagen,ja,2016-03-23 00:00:00,0,48249,2016-04-05 16:44:25
2016-03-05 14:47:40,BMW_M1_Replica_auch_als_Standmodel_im_Massstab...,privat,Angebot,0,control,NaN,1985,NaN,0,m_reihe,"100,000km",0,NaN,bmw,NaN,2016-03-05 00:00:00,0,23683,2016-04-07 09:45:44
2016-03-23 10:43:51,Opel_Corsa_fuer_Bastler_in_schwarz,privat,Angebot,0,control,NaN,2016,manuell,0,corsa,"150,000km",5,benzin,opel,NaN,2016-03-23 00:00:00,0,47906,2016-03-30 18:47:33

In [60]:
autos['registration_year'].describe()

count    49468.000000
mean      2003.222629
std          7.586435
min       1910.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       2017.000000
Name: registration_year, dtype: float64

In [62]:
autos_major_brands = autos_major_brands[(autos_major_brands.registration_year < 2018)]
autos_major_brands = autos_major_brands[(autos_major_brands.registration_year > 1901)]

In [64]:
autos_major_brands.price = [x.strip('$') for x in autos_major_brands.price]

In [65]:
autos_major_brands.price = autos_major_brands.price.str.replace(',','')
autos_major_brands['price'] = pd.to_numeric(autos_major_brands['price'])

In [66]:
autos_major_brands = autos_major_brands[(autos_major_brands.price < 500000)]

In [73]:
autos_major_brands.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38831 entries, 2016-03-26 17:47:46 to 2016-03-14 00:42:12
Data columns (total 19 columns):
name                  38831 non-null object
seller                38831 non-null object
offer_type            38831 non-null object
price                 38831 non-null int64
abtest                38831 non-null object
vehicle_type          35226 non-null object
registration_year     38831 non-null int64
gearbox               36909 non-null object
powerPS               38831 non-null int64
model                 37154 non-null object
odometer              38831 non-null object
registration_month    38831 non-null int64
fuel_type             35510 non-null object
brand                 38831 non-null object
unrepaired_damage     31072 non-null object
ad_created            38831 non-null object
nr_of_pictures        38831 non-null int64
postal_code           38831 non-null int64
last_seen             38831 non-null object
dtypes: int64(6), object(13)
memory usage: 5.9+ MB

In [91]:
brands_mean_price = autos_major_brands.groupby('brand').mean()[['price']].sort_values(by='brand', ascending=False)

In [93]:
print(brands_mean_price)

                     price
brand
volkswagen     5177.634858
renault        2364.367821
peugeot        3014.338164
opel           2853.815399
mercedes_benz  8384.584346
ford           3632.718469
fiat           2693.495726
bmw            8051.632664
audi           8989.552891

In [74]:
autos_major_brands.odometer = [x.strip('km') for x in autos_major_brands.odometer]

In [75]:
autos_major_brands.odometer = autos_major_brands.odometer.str.replace(',','')
autos_major_brands['odometer'] = pd.to_numeric(autos_major_brands['odometer'])

In [90]:
autos_major_brands.head()

,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
dateCrawled,,,,,,,,,,,,,,,,,,,
2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,300,test,limousine,1995,manuell,90,golf,150000,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59

In [88]:
brands_mean_mileage = autos_major_brands.groupby('brand').mean()[['odometer']].round(2).sort_values(by='brand', ascending=False)

In [89]:
brands_mean_mileage

                odometer
brand
volkswagen     128970.46
renault        128230.57
peugeot        127311.94
opel           129322.82
mercedes_benz  131037.53
ford           124079.44
fiat           116810.41
bmw            132517.65
audi           129561.59

In [96]:
brands_mean_prices_mileage = pd.concat([brands_mean_mileage, brands_mean_price], axis=1)

In [97]:
brands_mean_prices_mileage

                odometer        price
brand
volkswagen     128970.46  5177.634858
renault        128230.57  2364.367821
peugeot        127311.94  3014.338164
opel           129322.82  2853.815399
mercedes_benz  131037.53  8384.584346
ford           124079.44  3632.718469
fiat           116810.41  2693.495726
bmw            132517.65  8051.632664
audi           129561.59  8989.552891

In [98]:
%%capture
! pip install seaborn

In [99]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [105]:
brands_mean_prices_mileage.plt
plt.show()

AttributeError: 'DataFrame' object has no attribute 'plt'

#### Damaged vs non damaged